server:
    port: 9010
spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/AnthonyZero/spring-cloud-examples/     # git 仓库地址
                    search-paths: config-repo           # git仓库地址下的相对地址,可配置多个用,分割                  
                    username:           # 访问获取属性 http://localhost:9010/config/dev 获取 http://localhost:9010/config-dev.properties                                   
                    password:              